package enums

enum class RequestHttpHeaders(val headersKeys: String) {
    ACCEPT("Accept"),
    ACCEPT_CHARSET("Accept-Charset"),
    ACCEPT_ENCODING("Accept-Encoding"),
    CONTENT_LENGTH("Content-Length"),
    CONTENT_TYPE("Content-Type")
}

enum class HttpStatus(val error: Int, val description: String) {
    CONTINUE(100,	"Continue"),
    OK(200,	"OK"),
    CREATED(201,	"Created"),
    ACCEPTED(202,	"Accepted"),
    NON_AUTHORITATIVE_INFORMATION(203,	"Non-Authoritative Information"),
    FOUND(302,	"Found"),
    BAD_REQUEST(400,	"Bad Request"),
    UNAUTHORIZED(401,	"Unauthorized"),
    FORBIDDEN(403,	"Forbidden"),
    NOT_FOUND(404,	"Not Found"),
    METHOD_NOT_ALLOWED(405,	"Method Not Allowed"),
    NOT_ACCEPTABLE(406,	"Not Acceptable"),
    REQUEST_TIMEOUT(408,	"Request Timeout"),
    CONFLICT(409,	"Conflict"),
    LENGTH_REQUIRED(411,	"Length Required"),
    PAYLOAD_TOO_LARGE(413,	"Payload Too Large"),
    URI_TOO_LONG(414,	"URI Too Long"),
    UNSUPPORTED_MEDIA_TYPE(415,	"Unsupported Media Type"),
    RANGE_NOT_SATISFIABLE(416,	"Range Not Satisfiable"),
    EXPECTATION_FAILED(417,	"Expectation Failed"),
    UPGRADE_REQUIRED(426,	"Upgrade Required"),
    INTERNAL_SERVER_ERROR(500,	"Internal Server Error"),
    NOT_IMPLEMENTED(501,	"Not Implemented"),
    BAD_GATEWAY(502,	"Bad Gateway"),
    SERVICE_UNAVAILABLE(503,	"Service Unavailable"),
    GATEWAY_TIMEOUT(504,	"Gateway Timeout"),
    HTTP_VERSION_NOT_SUPPORTED(505,	"HTTP Version Not Supported");
}

enum class HttpVersion(val string: String) {
    HTTP_1_1("HTTP/1.1")
}

enum class HttpMethod {
    GET,
    HEAD,
    POST,
    PUT,
    DELETE,
    CONNECT,
    OPTIONS,
    TRACE
}

enum class MimeType(val ext: String, val mime: String) {
    AAC(".aac", "audio/aac"),
    ABW(".abw", "application/x-abiword"),
    ARC(".arc", "application/x-freearc"),
    AVI(".avi", "video/x-msvideo"),
    AZW(".azw", "application/vnd.amazon.ebook"),
    BIN(".bin", "application/octet-stream"),
    BMP(".bmp", "image/bmp"),
    BZ(".bz", "application/x-bzip"),
    BZ2(".bz2", "application/x-bzip2"),
    CSH(".csh", "application/x-csh"),
    CSS(".css", "text/css"),
    CSV(".csv", "text/csv"),
    DOC(".doc", "application/msword"),
    DOCX(".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
    EOT(".eot", "application/vnd.ms-fontobject"),
    EPUB(".epub", "application/epub+zip"),
    GZ(".gz", "application/gzip"),
    GIF(".gif", "image/gif"),
    HTM(".htm", "text/html"),
    HTML(".html", "text/html"),
    ICO(".ico", "image/vnd.microsoft.icon"),
    ICS(".ics", "text/calendar"),
    JAR(".jar", "application/java-archive"),
    JPEG(".jpeg", "image/jpeg"),
    JPG(".jpg", "image/jpeg"),
    JS(".js", "text/javascript"),
    JSON(".json", "application/json"),
    JSONLD(".jsonld", "application/ld+json"),
    MID(".mid", "audio/midi audio/x-midi"),
    MIDI(".midi", "audio/midi audio/x-midi"),
    MJS(".mjs", "text/javascript"),
    MP3(".mp3", "audio/mpeg"),
    MPEG(".mpeg", "video/mpeg"),
    MPKG(".mpkg", "application/vnd.apple.installer+xml"),
    ODP(".odp", "application/vnd.oasis.opendocument.presentation"),
    ODS(".ods", "application/vnd.oasis.opendocument.spreadsheet"),
    ODT(".odt", "application/vnd.oasis.opendocument.text"),
    OGA(".oga", "audio/ogg"),
    OGV(".ogv", "video/ogg"),
    OGX(".ogx", "application/ogg"),
    OPUS(".opus", "audio/opus"),
    OTF(".otf", "font/otf"),
    PNG(".png", "image/png"),
    PDF(".pdf", "application/pdf"),
    PHP(".php", "application/x-httpd-php"),
    PPT(".ppt", "application/vnd.ms-powerpoint"),
    PPTX(".pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation"),
    RAR(".rar", "application/vnd.rar"),
    RTF(".rtf", "application/rtf"),
    SH(".sh", "application/x-sh"),
    SVG(".svg", "image/svg+xml"),
    SWF(".swf", "application/x-shockwave-flash"),
    TAR(".tar", "application/x-tar"),
    TIF(".tif", "image/tiff"),
    TIFF(".tiff", "image/tiff"),
    TS(".ts", "video/mp2t"),
    TTF(".ttf", "font/ttf"),
    TXT(".txt", "text/plain"),
    VSD(".vsd", "application/vnd.visio"),
    WAV(".wav", "audio/wav"),
    WEBA(".weba", "audio/webm"),
    WEBM(".webm", "video/webm"),
    WEBP(".webp", "image/webp"),
    WOFF(".woff", "font/woff"),
    WOFF2(".woff2", "font/woff2"),
    XHTML(".xhtml", "application/xhtml+xml"),
    XLS(".xls", "application/vnd.ms-excel"),
    XLSX(".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
    XML(".xml", "application/xml"),
    XUL(".xul", "application/vnd.mozilla.xul+xml"),
    ZIP(".zip", "application/zip"),
    F3GP(".3gp", "video/3gpp"),
    F3G2(".3g2", "video/3gpp2"),
    F7Z(".7z", "application/x-7z-compressed");
}